/**
 * Role to Permission Mapping
 *
 * Defines which permissions each role has access to.
 * Based on the approved RBAC document for Wondrous/Trainer Aide.
 */

import { UserRole, Permission } from './types'
import { PERMISSIONS, PERMISSION_GROUPS } from './constants'

/**
 * Complete role-to-permission mapping
 */
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  // Super Admin - Full access to everything
  super_admin: [
    PERMISSIONS.ADMIN.FULL_ACCESS,
    ...PERMISSION_GROUPS.FULL_TRAINER_AIDE,
    ...PERMISSION_GROUPS.FULL_CLIENT_MANAGEMENT,
    ...PERMISSION_GROUPS.FULL_BOOKING_MANAGEMENT,
    PERMISSIONS.SCHEDULE.VIEW,
    PERMISSIONS.SCHEDULE.MANAGE,
    PERMISSIONS.SERVICES.VIEW,
    PERMISSIONS.SERVICES.CREATE,
    PERMISSIONS.SERVICES.EDIT,
    PERMISSIONS.SERVICES.DELETE,
    PERMISSIONS.PACKAGES.VIEW,
    PERMISSIONS.PACKAGES.CREATE,
    PERMISSIONS.PACKAGES.EDIT,
    PERMISSIONS.PACKAGES.DELETE,
    PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.TEAM.INVITE,
    PERMISSIONS.TEAM.MANAGE,
    PERMISSIONS.TEAM.REMOVE,
    PERMISSIONS.LOCATIONS.VIEW,
    PERMISSIONS.LOCATIONS.CREATE,
    PERMISSIONS.LOCATIONS.EDIT,
    PERMISSIONS.LOCATIONS.DELETE,
    PERMISSIONS.SETTINGS.VIEW,
    PERMISSIONS.SETTINGS.EDIT,
    PERMISSIONS.FINANCE.VIEW,
    PERMISSIONS.FINANCE.MANAGE,
  ],

  // Solo Practitioner - Acts as their own studio
  // Full access but no team/multi-location features
  solo_practitioner: [
    ...PERMISSION_GROUPS.FULL_TRAINER_AIDE,
    ...PERMISSION_GROUPS.FULL_CLIENT_MANAGEMENT,
    ...PERMISSION_GROUPS.FULL_BOOKING_MANAGEMENT,
    PERMISSIONS.SCHEDULE.VIEW,
    PERMISSIONS.SCHEDULE.MANAGE,
    PERMISSIONS.SERVICES.VIEW,
    PERMISSIONS.SERVICES.CREATE,
    PERMISSIONS.SERVICES.EDIT,
    PERMISSIONS.SERVICES.DELETE,
    PERMISSIONS.PACKAGES.VIEW,
    PERMISSIONS.PACKAGES.CREATE,
    PERMISSIONS.PACKAGES.EDIT,
    PERMISSIONS.PACKAGES.DELETE,
    PERMISSIONS.SETTINGS.VIEW,
    PERMISSIONS.SETTINGS.EDIT,
    PERMISSIONS.FINANCE.VIEW,
    PERMISSIONS.FINANCE.MANAGE,
    // Note: No TEAM or LOCATIONS permissions
  ],

  // Studio Owner - Full access to their studio(s)
  studio_owner: [
    ...PERMISSION_GROUPS.FULL_TRAINER_AIDE,
    ...PERMISSION_GROUPS.FULL_CLIENT_MANAGEMENT,
    ...PERMISSION_GROUPS.FULL_BOOKING_MANAGEMENT,
    PERMISSIONS.SCHEDULE.VIEW,
    PERMISSIONS.SCHEDULE.MANAGE,
    PERMISSIONS.SERVICES.VIEW,
    PERMISSIONS.SERVICES.CREATE,
    PERMISSIONS.SERVICES.EDIT,
    PERMISSIONS.SERVICES.DELETE,
    PERMISSIONS.PACKAGES.VIEW,
    PERMISSIONS.PACKAGES.CREATE,
    PERMISSIONS.PACKAGES.EDIT,
    PERMISSIONS.PACKAGES.DELETE,
    PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.TEAM.INVITE,
    PERMISSIONS.TEAM.MANAGE,
    PERMISSIONS.TEAM.REMOVE,
    PERMISSIONS.LOCATIONS.VIEW,
    PERMISSIONS.LOCATIONS.CREATE,
    PERMISSIONS.LOCATIONS.EDIT,
    PERMISSIONS.LOCATIONS.DELETE,
    PERMISSIONS.SETTINGS.VIEW,
    PERMISSIONS.SETTINGS.EDIT,
    PERMISSIONS.FINANCE.VIEW,
    PERMISSIONS.FINANCE.MANAGE,
  ],

  // Studio Manager - Manages operations but can't delete studio
  studio_manager: [
    ...PERMISSION_GROUPS.FULL_TRAINER_AIDE,
    ...PERMISSION_GROUPS.FULL_CLIENT_MANAGEMENT,
    ...PERMISSION_GROUPS.FULL_BOOKING_MANAGEMENT,
    PERMISSIONS.SCHEDULE.VIEW,
    PERMISSIONS.SCHEDULE.MANAGE,
    PERMISSIONS.SERVICES.VIEW,
    PERMISSIONS.SERVICES.CREATE,
    PERMISSIONS.SERVICES.EDIT,
    PERMISSIONS.PACKAGES.VIEW,
    PERMISSIONS.PACKAGES.CREATE,
    PERMISSIONS.PACKAGES.EDIT,
    PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.TEAM.INVITE,
    PERMISSIONS.TEAM.MANAGE,
    PERMISSIONS.LOCATIONS.VIEW,
    PERMISSIONS.SETTINGS.VIEW,
    PERMISSIONS.FINANCE.VIEW,
  ],

  // Trainer - Conducts sessions, manages their clients
  trainer: [
    ...PERMISSION_GROUPS.SESSION_EXECUTION,
    PERMISSIONS.TRAINER_AIDE.ASSIGN_TO_CLIENTS,
    PERMISSIONS.CLIENTS.VIEW,
    PERMISSIONS.CLIENTS.CREATE,
    PERMISSIONS.CLIENTS.EDIT,
    PERMISSIONS.BOOKINGS.VIEW,
    PERMISSIONS.BOOKINGS.CREATE,
    PERMISSIONS.BOOKINGS.EDIT,
    PERMISSIONS.SCHEDULE.VIEW,
    PERMISSIONS.SERVICES.VIEW,
    PERMISSIONS.PACKAGES.VIEW,
    PERMISSIONS.SETTINGS.VIEW,
  ],

  // Receptionist - Front desk operations
  receptionist: [
    PERMISSIONS.TRAINER_AIDE.VIEW_TEMPLATES,
    PERMISSIONS.TRAINER_AIDE.VIEW_SESSIONS,
    PERMISSIONS.CLIENTS.VIEW,
    PERMISSIONS.CLIENTS.CREATE,
    PERMISSIONS.CLIENTS.EDIT,
    PERMISSIONS.BOOKINGS.VIEW,
    PERMISSIONS.BOOKINGS.CREATE,
    PERMISSIONS.BOOKINGS.EDIT,
    PERMISSIONS.BOOKINGS.CANCEL,
    PERMISSIONS.SCHEDULE.VIEW,
    PERMISSIONS.SERVICES.VIEW,
    PERMISSIONS.PACKAGES.VIEW,
    PERMISSIONS.SETTINGS.VIEW,
  ],

  // Finance Manager - Financial operations
  finance_manager: [
    PERMISSIONS.TRAINER_AIDE.VIEW_TEMPLATES,
    PERMISSIONS.TRAINER_AIDE.VIEW_SESSIONS,
    PERMISSIONS.CLIENTS.VIEW,
    PERMISSIONS.BOOKINGS.VIEW,
    PERMISSIONS.SERVICES.VIEW,
    PERMISSIONS.PACKAGES.VIEW,
    PERMISSIONS.SETTINGS.VIEW,
    PERMISSIONS.FINANCE.VIEW,
    PERMISSIONS.FINANCE.MANAGE,
  ],

  // Client - View their own data
  client: [
    PERMISSIONS.TRAINER_AIDE.VIEW_PROGRESS,
    PERMISSIONS.TRAINER_AIDE.VIEW_SESSIONS,
    PERMISSIONS.BOOKINGS.VIEW,
    PERMISSIONS.BOOKINGS.CREATE,
    PERMISSIONS.SCHEDULE.VIEW,
    PERMISSIONS.SERVICES.VIEW,
    PERMISSIONS.PACKAGES.VIEW,
    PERMISSIONS.SETTINGS.VIEW,
    PERMISSIONS.SETTINGS.EDIT, // Own profile only
  ],
}

/**
 * Get all permissions for a role
 */
export function getPermissionsForRole(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] || []
}
